spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: darkevil

    jpa:
        generate-ddl: true
        show-sql: true
        
        hibernate:
            ddl-auto: create
        properties:
            hibernate: 
                dialect: org.hibernate.dialect.MySQL5Dialect

