spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ata_tbl
        username: root
        password: admin

    jpa:
        generate-ddl: true
        show-sql: true
        
        hibernate:
            ddl-auto: create
        properties:
            hibernate: 
                dialect: org.hibernate.dialect.MySQL5Dialect

